rule multiqc:
    input:
        expand(
           f"{results_dir}/fastqc_qc/{{sample}}_R1.html",
           sample=sample_data.index.tolist(),
        ),
        expand(
            f"{results_dir}/fastqc_qc/{{sample}}_R2.html",
            sample=sample_data.index.tolist(),
        ),
        expand(
            f"{results_dir}/fastp/{{sample}}_fastp.json",
            sample=sample_data.index.tolist(),
        ),
        get_minimap_output,
        f"{results_dir}/summary/summary_samples_mqc.txt",
        f"{results_dir}/summary/summary_contigs_mqc.txt",
        f"{results_dir}/summary/summary_gene_counts_mqc.txt",
        get_plot_tree_output,
        config="config/config_multiqc.yaml",
    output:
        f"{results_dir}/multiqc/multiqc_report.html",
        directory(f"{results_dir}/multiqc_data/"),
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
    log:
        "logs/multiqc.log",
    wrapper:
        "v7.5.0/bio/multiqc"
