# path to sample sheet csv with columns for ID,forward,reverse,seed,gene
samples: <samples>

# name of output directory
output_dir: <output_dir>

# fastp depulication (True/False)
fastp_dedup: <fastp_dedup>

# GetOrganelle target sequence type (mitochondrion, ribosomal)
target_type: <target_type>

# mitos refseq database (refseq39, refseq63f, refseq63m, refseq63o, refseq89f, refseq89m, refseq89o)
mitos_refseq: <mitos_refseq>

# mito code (2 = Vertebrate, 4 = Mold, 5 = Invertebrate, 9 = Echinoderm, 13 = Ascidian, 14 = Alternative flatworm
mitos_code: <mitos_code>

# barrnap kindgom (Bacteria:bac, Archaea:arc, Eukaryota:euk, None:NA)
barrnap_kingdom: <barrnap_kingdom>

# alignment trimming method to use (gblocks or clipkit)
alignment_trim: <alignment_trim>

# alignment missing data threshold for alignment (0.0 - 1.0)
missing_threshold: <missing_threshold>

# name of outgroup sample (optional)
# use "NA" if there is no obvious outgroup
# if more than one outgroup use a comma separated list i.e. "sampleA,sampleB"
outgroup: <outgroup>

# plot dimensions (cm)
plot_height: <plot_height>
plot_width: <plot_width>

# number of threads to use
threads: <threads>
