# name of input directory containg aligned genes
input_dir: <input_dir>

# name of output directory
output_dir: <output_dir>

# realign (True or False)
realign: <realign>

# alignment missing data threshold for alignment (0.0 - 1.0), only required if realign == True
missing_threshold: <missing_threshold>

# alignment trimming method to use (gblocks or clipkit), only required if realign == True
alignment_trim: <alignment_trim>

# name of outgroup sample (optional)
# use "NA" if there is no obvious outgroup
# if more than one outgroup use a comma separated list i.e. "sampleA,sampleB"
outgroup: <outgroup>

# plot dimensions (cm)
plot_height: <plot_height>
plot_width: <plot_width>

