# path to sample sheet csv with columns for ID,forward,reverse
samples: example_data/samples_mitochondrion.csv

# name of output directory
output_dir: results_mitochondrion_example

# fastp depulication (True/False)
fastp_dedup: True

# GetOrganelle target sequence type (mitochondrion, ribosomal)
target_type: mitochondrion

# mitos refseq database (refseq39, refseq63f, refseq63m, refseq63o, refseq89f, refseq89m, refseq89o)
mitos_refseq: refseq39

# mito code (2 = Vertebrate, 4 = Mold, 5 = Invertebrate, 9 = Echinoderm, 13 = Ascidian, 14 = Alternative flatworm
mitos_code: 5

# barrnap kindgom (Bacteria:bac, Archaea:arc, Eukaryota:euk, Metazoan Mitochondria:mito)
barrnap_kingdom: NA

# alignment trimming method to use (gblocks or clipkit)
alignment_trim: gblocks

# alignment missing data threshold for alignment (0.0 - 1.0)
missing_threshold: 0.5

# number of threads to use
threads: 6
