# path to sample sheet csv with columns for ID,forward,reverse,seed,gene
samples: example_data/samples_ribosomal.csv 

# name of output directory
output_dir: results_ribosomal_example

# fastp depulication (True/False)
fastp_dedup: True

# GetOrganelle target sequence type (mitochondrion, ribosomal)
target_type: ribosomal

# mitos refseq database (refseq39, refseq63f, refseq63m, refseq63o, refseq89f, refseq89m, refseq89o)
mitos_refseq: NA

# mito code (2 = Vertebrate, 4 = Mold, 5 = Invertebrate, 9 = Echinoderm, 13 = Ascidian, 14 = Alternative flatworm
mitos_code: NA

# barrnap kindgom (Bacteria:bac, Archaea:arc, Eukaryota:euk, Metazoan Mitochondria:mito)
barrnap_kingdom: euk

# alignment trimming method to use (gblocks or clipkit)
alignment_trim: gblocks

# name of outgroup sample (optional)
# use "NA" if there is no obvious outgroup
# if more than one outgroup use a comma separated list i.e. "sampleA,sampleB"
outgroup: "Eurema_blanda"

# plot dimensions (cm)
plot_height: 20
plot_width: 20

# alignment missing data threshold for alignment (0.0 - 1.0)
missing_threshold: 0.5

# number of threads to use
threads: 6
