# path to sample sheet csv with columns for ID,forward,reverse
samples: example_data/samples_example.csv

# name of output directory
output_dir: results_example

# GetOrganelle target sequence type (animal_mt,embplant_cp,anonym)
target_type: animal_mt

# path to blast db
blast_db: refseq_mitochondrion/refseq_mitochondrion

# path to new_taxdump
taxdump: taxdump

# path to mitos refseq
mitos_refseq: refseq39

# mito code
mitos_code: 2

# barrnap kindgom (Bacteria:bac, Archaea:arc, Eukaryota:euk, Metazoan Mitochondria:mito)
barrnap_kingdom: NA

# alignment trimming method to use (gblocks or clipkit)
alignment_trim: gblocks

# number of threads to use
threads: 6

