channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3
  - graphviz =2.42
  - pandas =1.5.2
  - trf =4.09.1
  - biopython =1.80
