channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal =7.25.3
  - jinja2 =3.1.2
  - networkx =3.1
  - matplotlib =3.7.1
  - graphviz =8.0.5
  - pandas =2.0.1
  - trf =4.09.1
  - biopython =1.81

